### ISSUE TITLE
Make DCAT application profile suitable for metadata FLINT interpretation

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#127]
Consider these 2 examples with FLINT interpretation described conclusively. What metadata do I need to upload these interpretations into a [rule library](https://regels.dexcat.nl/) and make them findable there?

Examples:
- Strafblad inzage
  - UPL https://standaarden.overheid.nl/owms/terms/strafbladInz
  - Bron https://wetten.overheid.nl/BWBR0014194/2022-07-01/#Titeldeel2_Afdeling3_Artikel18
- Huurtoeslag
  - Berekenen huurtoeslag https://algoritmes.overheid.nl/algoritme/berekenen-huurtoeslag-ministerie-van-financien
  - UPL http://standaarden.overheid.nl/owms/terms/huurtoeslag
  - Bron https://wetten.overheid.nl/BWBR0008659/2023-01-01

Consider this [DCAT-AP-RONL (concept)](https://minbzk.github.io/dcat-ap-ronl/) profile as a standard specification of the aforementioned metadata

**Comment by robertvandoesburg** [comment]
**First reaction**
For the Flint ontologie, see [https://gitlab.com/calculemus-flint/knowledge-modeling/flint-ontology](https://gitlab.com/calculemus-flint/knowledge-modeling/flint-ontology).

In the coming weeks we will make some adjustments. After that I believe it will contain everything you need regarding metadata of Flint.

I will comment on the legal text in Dutch, see below

1. Artikel 18 lid 1 Wet justitiële en strafvorderlijke gegevens bevat:
    - verzoeken om uitsluitsel te verkrijgen over de al dan niet verwerking van hem betreffende justitiële gegevens (aanvraag zoals geregeld in de Awb)
    - inzien justitiële gegevens (is hier meer informatie over? Gaat het om je fysiek melden en dan ergens kijken naar papier of een scherm, of zijn er ook andere mogelijkheden? Waar kan ik hier meer over vinden, of moet ik me daar geen zorgen over maken en gewoon alleen interpreteren wat er staat?)
    - verkrijgen informatie als beschreven onder a t/m g van artikel 18 lid 1 (is relevant om te weten wat het verschil is tussen 'inzien' en 'verkrijgen', of interpreteer ik alleen de tekst die hier staat. Interpreteren zoals het er staat betekent dat ik er vanuit dat 'inzien' en 'verkrijgen' verschillende dingen zijn waarbij ik geen idee heb wat 'inzien' is en wat 'verkrijgen' anders dan de letters en de volgorde van de letters van die woorden).
    - het recht op verzoeken om verbetering, vernietiging of afscherming van de verwerking van hem betreffende persoonsgegevens
    - het recht een klacht in te dienen bij de Autoriteit persoonsgegevens
2. In lid 2 staan nog de handeling om het verzoek af te wijzen, en nog iets over "geen mededelingen in schriftelijke vorm over de verwerking van de betrokkene betreffende justitiële gegevens"
    - Wordt hier bedoeld 'betrokken' i.p.v. 'betrokkene'? (Als dit geen fout in de wetstekst is, heb ik wat hulp nodig om te begrijpen wat er staat.)
    - Ik neem aan dat 'hij' verwijst naar 'Onze Minister.
    - Als 'hij' 'Onze Minister' is en 'betrokkene' 'betrokken' dan begrijp ik dat er geen schriftelijke weergaven van de verwerking van justitiële gegevens wordt verstrekt, en dat de betrokkene om die te zien fysiek naar een locatie moet om die gegevens te bekijken.

Als je een korte toelichting geeft op de bovenstaande vragen, maak ik een Flint interpretatie.

**Comment by sgort** [comment]
Request for further explanation sent to colleague lawyer at Justid.

**Comment by bretelerjmw** [comment]
We started a [Calculemus ontology](https://gitlab.com/calculemus-flint/knowledge-modeling/calculemus-ontology) for organizing datasets related to carrying out a normative task; part of that is to interpret normative sources, which one could do using FLINT. I think we could link it to the DCAT (or PROV) concepts and we shouldn't need much if any special concepts on top of that.

Would it also help for the Application Profile to abstract to the level of "Interpretation"? And then, one implementation of the Interpretation would be to posit a set of rules?

@sgort if you are interested in us implementing PROV/DCAT for the Calculemus ontology, I would like to know when you could use it and what you could use it for (so we have some test cases to work towards).

---

Disclaimer to the DCAT-AP-RONL: FLINT frames are not rules. (although FLINT frames can represent (relatively loose/informal/natural-language-based) interpretations of regulations). Because of this, they also do not fit in the DCAT-AP-RONL draft linked above; there is no "input" or "output" and no "rule" (Regel) unit. And FLINT frames do not have an "execution" aspect (although eFLINT does).

**Comment by sgort** [comment]
Thanks for the addition. Did some thorough editing in the DCAT-AP-RONL profile and placed it in the normative part to better highlight this. Obviously that can be done even better. And eventually the explanation and visualization in the summary will also change...

**Comment by bretelerjmw** [comment]
Hi @sgort , 

I think this could be a helpful input for the current DCAT profile: a report of our first experiments on querying a graph database for Calculemus tasks. Does it answer your questions / raise new ones?

https://gitlab.com/calculemus-flint/knowledge-modeling/general/-/wikis/2022-12-repository

**Comment by sgort** [comment]
[Inzien strafblad](https://www.justid.nl/onderwerpen/strafblad-en-het-justitieel-documentatie-systeem/inzien-van-het-strafblad) state to date...

![image](https://user-images.githubusercontent.com/25812095/219090208-ae700cf8-f8f5-42c7-b947-e3d3ac5e9f19.png)
